### ISSUE TITLE
Website Request: https://chrysanthemumgarden.com/

### ISSUE THREAD

**Issue by 1jamie7** [mHaisham/novelsave#22]
Hi. 🤗 Is it possible to add this https://chrysanthemumgarden.com/ site?

**Comment by mHaisham** [comment]
I'll see to it as soon as i can... shouldnt take longer that a day

**Comment by 1jamie7** [comment]
Thank you so much. ❤

**Comment by 1jamie7** [comment]
I also would like to bring to your attention that https://chrysanthemumgarden.com/ has a protection in the form of a jumble code that makes some paragraphs gibberish in all the chapters.

**Comment by mHaisham** [comment]
Noted

**Comment by mHaisham** [comment]
The website uses a jumbled type face.

```css
@font-face{
    font-family: opensans-jumbld;
    src: url(fonts/OpenSans-Jumbld2.woff2) format('woff2'), url(fonts/OpenSans-Jumbld2.woff) format('woff'), url(fonts/OpenSans-Jumbld2.ttf) format('truetype');
    font-weight: 400;
    font-style: normal
}

.jum {
    font-family: opensans-jumbld!important;
}
```

They dont offer and .otf font file, which is the only type that supports epub

I could come with a workaround by creating a map.. but that is gonna take some time to fully map
